star_index: 'refs/indexes/STAR_gdc38_gencode38'
whitelist:
    v3: "resources/whitelist/whitelist.10x.v3.txt"
align_multi_starsolo:
    soloType: "CB_UMI_Simple"
    soloCBstart: 1
    soloCBlen: 16
    soloUMIstart: 17
    soloUMIlen: 12
    outSAMattributes: "NH HI nM AS CR UR CB UB GX GN sS sQ sM"
    outSAMtype: "BAM SortedByCoordinate"
    clipAdapterType: "CellRanger4"
    outFilterScoreMin: 30
    soloCBmatchWLtype: "1MM_multi_Nbase_pseudocounts"
    soloUMIfiltering: "MultiGeneUMI_CR"
    soloUMIdedup: "1MM_CR"
    limitOutSJcollapsed: 5000000
    outFilterMultimapScoreRange: 5
    outFilterMultimapNmax: 500
